
spring:
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://lagou.stave.tech:3306/lagou?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
    username: lagou
    password: LagouNewer123
  mail:
    host: smtp.qq.com
    username: 793863973
    password: ranohacdckuubdgb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  devtools:
    restart:
      enabled: true
  jackson:

    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true
mybatis:

  type-aliases-package: com.newer.lagou.domain
  configuration:

    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8086
  servlet:
    context-path:

logging:
  level:
    com.newer.hospital.mapper: debug
    org.springframework.security: info
jwt:
  #请求header所携带token的属性名
  header: Authorization
  #用户自定义的口令
  secret: mySecret
  #失效时间
  expiration: 604800
  #承载字符串
  tokenHead: Bearer
  route:
    authentication:
      #token授权url
      path: /auth
      #刷新token的url
      refresh: /refresh